DROP DATABASE IF EXISTS verigate_db;

CREATE DATABASE verigate_db;

USE verigate_db;

CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT,
    fname VARCHAR(45) NOT NULL,
    lname VARCHAR(45) NOT NULL,
    email VARCHAR(25) NOT NULL,
    pin INT(4) NOT NULL, -- 4 DIGIT PIN CODE (DEFAULT IN SEEDS.SQL IS 1234)
    switch BOOLEAN DEFAULT FALSE, -- BOOL TO STORE THE CURRENT STATE OF THE RELAY(LED)
    ssid VARCHAR(255), -- USER STORED SSID
    pass VARCHAR(255), -- USER STORED WI-FI PASSWORD
    PRIMARY KEY (id)
);


