DROP DATABASE IF EXISTS verigate_db;

CREATE DATABASE verigate_db;

USE verigate_db;

CREATE TABLE admin (
    admin_id INT NOT NULL AUTO_INCREMENT,
    fname VARCHAR(45) NOT NULL,
    lname VARCHAR(45) NOT NULL,
    email VARCHAR(100) NOT NULL,
    pin INT(4) NOT NULL, -- 4 DIGIT PIN CODE (DEFAULT IN SEEDS.SQL IS 1234)
    switch BOOLEAN DEFAULT FALSE, -- BOOL TO STORE THE CURRENT STATE OF THE RELAY(LED)
    ssid VARCHAR(255), -- USER STORED SSID
    pass VARCHAR(255), -- USER STORED WI-FI PASSWORD
    PRIMARY KEY (admin_id)
);

CREATE TABLE users (
    user_id INT NOT NULL AUTO_INCREMENT,
    fname VARCHAR(45) NOT NULL,
    lname VARCHAR(45) NOT NULL,
    email VARCHAR(100) NOT NULL,
    pin INT(4) NOT NULL, -- 4 DIGIT PIN CODE (DEFAULT IN SEEDS.SQL IS 1234)
    admin_id INT NOT NULL,
    PRIMARY KEY (user_id),
    FOREIGN KEY (admin_id) REFERENCES admin(admin_id)
);
